travis:
  secure:
    BINSTAR_TOKEN: A43CFGda07cvV+wLpn1mdHWRRpEbgOqCOO3xAHZ3sVEGEzL23o2rq7mNmYBQSkbansvzQbz8cIAtzJbqWUMb+7uQeyxbGYiKZXWtr3TmfiRLl0VLJ9hKB5MOt75asrChzX05kgMLVEXNm2Q9A2hAFlL7t5xpOVgaPy/TH/Y8vbzvp80pbgPqPhHVxpA9h1GdFwsZ5LC6YubAU1aSNxJH3F+ANcA0cRzVF0Y26HF0Jz6YRMrU9QWxjqs0NGIZwf69gkzAxQ9cBE8emaEqJ8a8ob7wldb1TXPHiGkJTlZmDR9h5dO364/OoxrosO6BhFDoTQu9L/ojCB2519AQzeW9kfY2HnEhUyiTG6JPIGez3KSwnE9lW8eSWmIHybF+72JjewDwn/QgOMqCkHLEoKNP6uv6HYRrxE/uzoIfh1EUdyeYGwq2dhAgOAHe35d0OID/dnCrhCsXLkyQGkLNvhsiReLbHxLk25WjuiJfT/StdrKznH9oEB7QxOfvprv/A333h5B3QM9WwUm1hlO5c9FtmZypNrMvwZ+h8Xn84nZTnVDTh9UO2AT0If6qtX2SDYq9/7vmGr1uVz7D7rVbNxulucYcICpzt4m3B1TEW4HA5eb0aTkPByEF1f2EdrxXRfNjYCVVFoyMEewyGl7iU4Si4gUX1gzC1MJpAvGYKBOU7Xo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
